# ev at step level
name: Variables and secrets
on: 
    push
jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Docker build
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IMAGE_NAME: github-actions-ngnix
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        - name: Docker login
          env:
            DOCKER_PASSWORD: s3cUrePaSsw0rd
            DOCKER_USERNAME: siddharth1
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        - name: Docker publish
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IMAGE_NAME: github-actions-ngnix
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Docker run
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IMAGE_NAME: github-actions-ngnix
          run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

# ev at job level
name: Variables and secrets
on: 
    push
jobs:
    docker:
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: siddharth1
        IMAGE_NAME: github-actions-ngnix
      runs-on: ubuntu-latest
      steps:
        - name: Docker build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        - name: Docker login
          env:
            DOCKER_PASSWORD: s3cUrePaSsw0rd
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        - name: Docker publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    deploy:
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: siddharth1
        IMAGE_NAME: github-actions-ngnix
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Docker run
          run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

          
# ev at workflow level
name: Variables and secrets
on:
  push
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: siddharth1
  IMAGE_NAME: github-actions-ngnix
jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Docker build
          run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest
        - name: Docker login
          env:
            DOCKER_PASSWORD: s3cUrePaSsw0rd
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        - name: Docker publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    deploy:
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: siddharth1
        IMAGE_NAME: github-actions-ngnix
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Docker run
          run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest        
